version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: wolf_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: wolf_api
    restart: always
    env_file:
      - ./server/.env.production
    environment:
      - UPLOADS_DIR=/app/uploads  # container path
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - appnet
    volumes:
      - /opt/wolf-supplies/server/uploads:/app/uploads  # host : container path
    user: "1000:1000"  # optional: ensures Node container can write to uploads folder

volumes:
  mongo_data:

networks:
  appnet:
    driver: bridge
